# Generated by Django 5.0.6 on 2024-06-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_exercise_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessuser',
            name='selected_equipment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fitnessuser',
            name='selected_muscle_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fitnessuser',
            name='workout_history',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
