# Generated by Django 5.0.6 on 2024-06-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_fitnessuser_selected_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessuser',
            name='city',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
