# Generated by Django 5.0.6 on 2024-06-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_fitnessuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessuser',
            name='tracker',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
