# Generated by Django 5.0.6 on 2024-07-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_dailyworkout_exercises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='muscle_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
