# Generated by Django 5.0.6 on 2024-07-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_workout_muscle_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
