# Generated by Django 5.0.6 on 2024-07-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_fitnessuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_weighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutdetail',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
